### ISSUE TITLE
SecurityException Permission Denial: startForeground requires android.permission.FOREGROUND_SERVICE

### ISSUE THREAD

**Issue by PinkalBaleshwaria** [alexbbb/android-upload-service#421]
### 3.4.2
* Android Upload Service version: 3.4.2
* Android version and API version: Android 9(Pie) Target API version: 28
* HTTP stack (e.g. HurlStack or OkHttpStack): HurlStack

### Steps to reproduce (if applicable):
Working perfect on below 8.1 devices, I got above exception on 8.1 devices because of Background service changes introduced in Android 8.1

// the code you wrote to create the upload request
int mLastJobId = new JobRequest.Builder(UploadJob.TAG)
                    .startNow()
                    .build()
                    .schedule();

#### Where have you added the request code?
- [ True ] Activity
- [ ] Service
- [ ] Other class (add additional info about it)

// your LogCat output here
### Stack Trace
 java.lang.SecurityException: Permission Denial: startForeground from pid=13097, uid=10300 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5198)
        at android.app.Service.startForeground(Service.java:695)
        at net.gotev.uploadservice.UploadService.holdForegroundNotification(UploadService.java:388)
        at net.gotev.uploadservice.UploadTask.createNotification(UploadTask.java:469)
        at net.gotev.uploadservice.UploadTask.run(UploadTask.java:145)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by gotev** [comment]
@PinkalBaleshwaria This can be added to the library's manifest for newer Androids. Can you make a PR?

**Comment by gotev** [comment]
Never mind. Done it myself. Version `3.5.0` has the required permission for Android 9 already integrated.

**Comment by felixdivo** [comment]
Cool, thank you!
